spring:
  application:
    name: eureka-server
server:
  port: 1111
eureka:
  instance:
#    hostname: peer1
    hostname: 127.0.0.1
  client:
    serviceurl:
      defaultZone: http://127.0.0.1:1112/eureka/

