server:
  port: 8080
spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/data_range?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: admin
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: ac.iie.server.domain
logging:
  config: classpath:log4j2-test.xml
yaml:
   effective:
    - www.baidu.com
    - www.toutiao.com
   extractUserRule: { "www.baidu.com":"select * from", "www.toutiao.com":"select * from"}
   interfaceOuterAddress: { "www.baidu.com-1":"10.136.73.81", "www.toutiao.com-1":"10.136.73.81"}
   interfaceInnerAddress: { "isNomArticle":"10.136.73.81", "ss":"10.136.73.81"}
   maxThreads: 100



