server:
  port: 8080
spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/data_range?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: admin
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: ac.iie.server.domain
  configuration:
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    autoMappingUnknownColumnBehavior: WARNING
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  config: classpath:log4j2-test.xml
yaml:
   baseUrl: "J://work"
   zipDataUrl: "zip_data"
   logoUrl: "logo"
   dataUrl: "data"
   programUrl: "program"
   userAnswer: "userAnswer"
   cloudService: { ""}




