spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  jackson:
    serialization:
      indent_output: true
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3

zuul:
  routes:
    test:
      path: /test/**
      serviceId: test-service