eureka:
  client:
    service-url: defaultZone:http://localhost:8888/eureka/
spring:
  application:
    name: auth-service
profiles:
  active: ${SPRING_PROFILES_ACTIVE:dev}
datasource:
  username: root
  password: 123
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cloudauth
jpa:
  hibernate:
    ddl-auto: create-drop
    show-sql: true
redis:
  host: localhost
  port: 6379
server:
  port: 5000
security:
  oauth2:
    resource:
      filter-order: 3